export const states = {
  NEW_USER: "NEW_USER",
  EXPECT_USERNAME: "EXPECT_USERNAME",
  EXPECT_PASSWORD: "EXPECT_PASSWORD",
  LOGGED_IN: "LOGGED_IN",
};

export const DEFAULT_STATE = states.NEW_USER;
